class Solution {
public:

bool check (long long int mid,int k,int r,vector<long long>& diff,int n,vector<int> & stations){
    long long cummlativesum=0;
    vector<long long> tempdiff=diff;
    for (int i=0;i<n;i++){
        cummlativesum=cummlativesum+tempdiff[i];

        if (cummlativesum<mid){
            long long int need=mid-cummlativesum;

            if (need>k){
                return false;
            }
            k=k-need;
            cummlativesum+=need;
            // here in the next step i will try to be greedy as i will want to get the maximum power which is generated by the power stations

            if (i+2*r+1<n){
                tempdiff[i+2*r+1]=tempdiff[i+2*r+1]-need;
            }
        }
    }
    return true;
}

    long long maxPower(vector<int>& stations, int r, int k) {
        int n=stations.size();
        vector<long long> diff(n,0);

        for (int i=0;i<n;i++){ 
            diff[max(0,i-r)]=diff[max(0,i-r)]+stations[i];    // using dat technique
            if (i+r+1 <n){
                diff[i+r+1]=diff[i+r+1]-stations[i];     // using dat technique
            }
        }
        long long int left=0;
        long long int sum=0;
        for (int i=0;i<n;i++){
            sum=sum+stations[i];
        }
        long long int right=sum+k;
        long long int res=0;
        while(left<=right){
            long long int mid=left+(right-left)/2;

            if (check(mid,k,r,diff,n,stations)){
                res=mid;
                left=mid+1;
            }
            else {
                right=mid-1;
            }
        }
        return res;
    }
};